suricata: Autospec creation for update from version 6.0.4 to version 6.0.5
Angelo Mirabella (1):
      stream-tcp-reassemble: fix reassembly direction for FIN packets

Arne Welzel (1):
      flow-manager: fix off-by-one in flow_hash row allocation

Corey Thomas (1):
      ci: add fedora 35 to builds

Eloy Pérez González (6):
      smb/dce_opnum: use DCERPC_TYPE_REQUEST
      smb/dce_opnum: move range if to outer context
      smb/dce_iface: use DCERPC_TYPE_REQUEST
      smb/dce_iface: avoid deleting current ifaces from state
      dcerpc: avoid delete the rpc state interface context
      dcerpc: remove prev_tx_call_id and clear_bind_cache from DCERPCState

Eric Leblond (2):
      profiling: fix profiling with sample rate
      util/streaming: improve error handling

Jason Ish (23):
      ci: update Ubuntu 16.04 test to 20.04 with MSRV
      dhcp: fix url in comment
      smtp: log transaction even if no email present
      af-packet: use configured cluster-id when checking for fanout
      datasets: initialize after dropping privileges
      dns: create transaction even if z-bit was set
      dns: add dns flag to dns request logging
      github-ci: use curl -L for npcap: follow redirects
      startup: initialize run as user info sooner
      logging: change ownership of application log if needed
      detect-content: error on single char hex pairs
      smb: fix smb2 header flag parsing
      smb: expose smb1 request/reply flags with a method
      smb: handle records in the wrong direction
      smb: rules for messages in the wrong direction
      github-ci: pin checkout actions plus other fixups
      mqtt: ensure we do not request extra data after buffering
      app-layer: better warning message when enabling by default
      smb: protocol detection on pattern without midstream
      dns: better error handling when parsing names
      dns: don't parse a full request during probe if not enough data
      ftp: truncate command data that is too long
      doc/userguide: document ftp max-line-length

Jeff Lucovsky (22):
      suricatasc: Handle incomplete/empty recv values
      detect/file_data: Reject invalid protocols
      config/ref: Raise errors for ref.config parsing
      general: Fix typo
      doc: Describe per-thread stack size config setting
      config/debug: Debug probe for getattr_np
      suricata.yaml: Add per-thread stack size setting
      config/thread: Use config'd per-thread stack size
      threads: Honor per-thread stack size setting
      proto: Remove dependency on /etc/protocols
      error/hash: Add error code for hash add failures
      util/proto: Protocol-name functions
      detect/ipproto: Add init/release functions
      detect/tests: Register protoname tests
      detect/ipproto: Use builtin protocol table
      configure.ac: Support libunwind configuration
      error: Add error code for sig-related diagnostics
      logging: Stacktrace on signal term setting
      logging/diag: Enable stacktrace diagnostic if config'd
      doc/yaml: Signal-termination option description
      config: Make libunwind use configurable for 6.0
      log/stack: Propagate original signal

Modupe Falodun (1):
      detect-file-data: remove SMTP unittests

Odin Jenseg (2):
      dns: Logging of Z-bit
      doc/eve-json-format/dns: Describing Z-bit

Philippe Antoine (19):
      mqtt: fix transaction completion
      alert: fixes leak in ThresholdHandlePacketRule
      conf: avoid quadratic complexity
      mqtt: parse properties with the right buffer's length
      util: export Djb2 hash string function
      smtp: check if there is a transaction to close
      smtp: check if we have a current transaction
      fuzz: use fuzzing confyaml for protodetect target
      ssl: first pass limit when allocating buffer for certificates
      tftp: StringToAppProto case
      mqtt: fix consumed bytes computation for truncated msg
      tftp: use destate
      util: right parenthesises for base64 macro
      dnp3: check Base64Encode return value for logging
      ftp: do not set alproto if one was already found
      detect: only apply ConfigApplyTx with app-layers
      detect: makes config keyword really require a flow
      detect: not an iponly signature if it needs app-layer
      detect: config checks alstate before getting tx

Sascha Steinbiss (1):
      mqtt: raise event on parse error

Shivani Bhardwaj (14):
      rust: bump MSRV to 1.41.1
      ci: add Fedora 34 to builds
      ci: remove eol Fedora 32 & 33
      detect/proto: Warn if proto not found in config
      applayer: fix clang formatting
      doc: add usage of flowbits OR op
      detect/xbits: parse keywords w strtok_r
      doc/xbits: clarify noalert usage
      detect/dataset: fix space condition in rule lang
      detect/dataset: cleanup dead code
      smtp: use AppLayerResult instead of buffering
      smtp: add truncated line event
      smtp: fix indefinite buffering if no LF in line
      smtp: pre process DATA and BDAT commands

Steven Ottenhoff (1):
      pppoe: fix protocol field length variation

Victor Julien (60):
      version: start development towards 6.0.5
      mingw: add bcrypt to LDADD for rust compilation
      flow: immediately evict tcp reused flows
      flow/worker: run housekeeping for bypassed packets
      flow/bypass: add util func to check if flow is bypassed
      flow/bypass: clear memory on bypass
      stream: fix stream pruning being too aggressive
      github-ci: replace failing CentOS 8 by AlmaLinux 8.4
      util/cidr: simplify IPv4 CIDR handling; add IPv6
      radix: minor debug 'Print' improvements
      detect/iponly: minor debug 'Print' improvements
      detect/iponly: cleanups
      radix: fix FP/FN issue in IP-only
      radix: add tests for Bug #5066
      radix: cleanup test
      detect/iponly: update SigNumArray comment
      radix: fix unittest not cleaning up
      detect/iponly: fix netmask handling
      radix: improve address range handling
      radix: fix unittests after stict checks
      detect/address: use common cidr code
      output: fix timestamp missing usecs
      nfs4: verify bool fields
      nfs/rpc: enforce length field limits
      nfs: break out partial record handling
      nfs/rpc: update full record parsers to be more exact
      rpc: enforce various field values
      nfs3: enforce more values
      nfs3: fix partial write record handling
      nfs3: improve read validation; fix partial handling
      nfs: clean up partial record handling
      util/cidr: add util to convert netmask to cidr
      detect/iponly: break out range insert code
      detect/address: validate netmasks
      detect/iponly: validate netmask
      detect/address: minor unittest cleanup
      detect/iponly: add tests for 5170
      iprep: unify free handling
      detect/iprep: fix host locking issues
      decode: release refs from PacketFree
      unittests: clean up packet clear logic
      swf: fix coverity warnings
      smb1: apply close to direction
      nss: use 'atexit()' to cleanup
      flow: fix and simplify locking
      filetracker: make FileChunk private
      smb: minor function cleanup
      smb2: track max read/write size and enforce its values
      smb2: add options for max read/write size
      filetracker: track total queued data (in_flight)
      smb2: allow limiting in-flight data size/cnt
      smb2: validate negotiate read/write max sizes
      doc/smb: add resource limits section
      smb/rules: add rules for new events
      smb: log max read/write sizes
      smb: fix read queue exceeded event and rules
      mime: allow partial lines as input
      smtp: don't pass partial boundary on to mime parser
      smtp: support per-tx file accounting
      release: 6.0.5; update changelog; require htp 0.5.40