suricata: Autospec creation for update from version 7.0.0 to version 7.0.1
Alexandre Iooss (1):
      doc/userguide: improve SCStreamingBuffer example

Andreas Herz (2):
      doc: dataset - add type to be mandatory
      doc: add note about cpu prio overwrite behavior

Arne Welzel (1):
      community-id: Fix IPv6 address sorting not respecting byte order

Cole Dishington (1):
      decode-ipv6: Set L4 proto on ipv6 incase of GRE decode error

Jason Ish (7):
      doc/userguide: display version on front page
      github-ci: disable some workflows on doc only changes
      eve: fix double free of sensor-name on error
      eve/schema: add host
      configure: check for new enough sphinx-build
      configure: more idiomatic autoconf for sphinx-build checks
      readthedocs: pin theme to sphinx_rtd_theme

Jeff Lucovsky (13):
      detect/include: Remove unnecessary includes
      schema: Add memcap pressure values
      general/typo: Correct spelling/grammar issues
      mem/alloc: Replace malloc with calloc
      output/stats: Handle stat names w/out scope
      general: Remove unused include files
      gen/typos: Correct misc. typos.
      reputation: Release memory on key add fails
      gen/bool: Use bool type instead of ints
      error: Add SC_EEXIST for dups
      radix: Detect duplicate netblocks
      detect/analysis: Move globals to engine ctx
      build/nss: Remove libnss from CI

Juliana Fajardini (5):
      userguide/upgrade: link to exception policy FAQ
      docs: miscellanea updates
      userguide/install: add info on ubuntu ppa installs
      userguide/ppa: fix typo
      release: 7.0.1; update changelog

Lukas Sismis (2):
      dpdk: fix DPDK thread check for IPS mode
      dpdk: treat unknown socket ID as a valid socket ID

Philippe Antoine (11):
      decode: fix offset for DCE layer
      profiling: fix check to compute average bytes
      src: checks to avoid divisions by zero
      jsonschema: add missing field .files[].file_id
      output: add storing boolean for files
      mpm: allocate StateQueue on the heap
      rust: fix clippy warnings for version 1.72.0
      rdp: do not use zero-bit bitflag
      config/flow: fix division by zero
      fuzz: enable by default all protocols
      smtp: fix null deref with config option body md5

Ralph Eastwood (12):
      napatech: fix compilation errors in SCLog calls
      napatech: fix missing header includes
      napatech: fix compilation with SCTIME usage
      napatech: fix thread flags with THV_RUNNING
      napatech: fix warnings with ByteExtractStringUint8
      configure: move -lntapi to LIBS variable
      napatech: fix shadowed global is_inline warning
      napatech: generalise numa config recommending
      napatech: remove superfluous log messages
      napatech: fix incorrect fmt specifiers for log
      napatech: print NUMA recommendation early
      napatech: fix null-dereference of packet

Shivani Bhardwaj (4):
      dcerpc: accept ALTER_CONTEXT as a valid request
      af-packet: check out_iface not NULL
      af-packet: terminate on same interface & copyiface
      workflows: use s-v --debug-failed

Thomas Winter (1):
      iprep: fix parsing ip-rep data with carriage return

Victor Julien (35):
      version: start development towards 7.0.1
      sysfs: fix minor compile warning
      detect: fix minor compile warning
      mime: replace small memcpy with loop
      stats: simplify ips capture stats logic
      eve/schema: add ips capture stats
      stats: register ips capture stats for each packet thread
      stats: update ips capture counters centrally
      stats: add drop reason counters
      threads: improve spawn failure error reporting
      pcap/file: normalize file timestamps
      ftp: reenable debug check; improve debug log
      stream: add stream.rst_with_data event for RST with data
      stream: special handling for RST data
      rust: update cargo.lock
      dpdk/mlx5: fix shutdown crash in IPS mode
      detect/content: cleanup nocase conversion
      detect/file: use util to turn keyword to nocase
      detect/pcre: use local match data during parsing
      var-names: reimplement var name handling
      output: deinit last so logging can happen until the end
      threshold: fix multi-tenant file parsing
      threshold: minor code cleanups
      stat: add wrappers to isolate OS_WIN32 specifics
      path: new funcs to merge paths
      detect: free all tenant detect engines
      detect: add multi-detect.config-path
      multi-tenant: don't init config twice in tenant reload
      multi-tenant: allow reload w/o yaml path
      multi-tenant: add reload-tenants command
      doc/userguide: add reload-tenant(s) doc
      detect: fix path creation in Windows
      detect/loader: minor code cleanups
      threading: set min thread stack size; set it early
      spm/hs: don't exit on bad patterns

Yatin Kanetkar (1):
      dhcp: Log Vendor Client Identifier (dhcp option 60)

jason taylor (4):
      detect: update filename buffer description name
      doc: update file.name keyword information
      doc: update fileext keyword information
      doc: update file.magic information